// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTObpNulV8K-OVcwXI44la0U8SdmRHLuE',
    appId: '1:1023388273755:web:045b6b1bccebd858e7437e',
    messagingSenderId: '1023388273755',
    projectId: 'family-app-61374',
    authDomain: 'family-app-61374.firebaseapp.com',
    storageBucket: 'family-app-61374.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoaH5511elJHS6_QeHwHYpZEWaB3Ilttw',
    appId: '1:1023388273755:android:c65fbcda403a5572e7437e',
    messagingSenderId: '1023388273755',
    projectId: 'family-app-61374',
    storageBucket: 'family-app-61374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB_-UXvbZLop2ncPVjYZQYaedc8D8YT_E',
    appId: '1:1023388273755:ios:4dafd31f15cae804e7437e',
    messagingSenderId: '1023388273755',
    projectId: 'family-app-61374',
    storageBucket: 'family-app-61374.appspot.com',
    iosClientId: '1023388273755-4e4i0tc7b5rlept6jdin8ecu4sio7do9.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekt',
  );
}
